import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart' show Scaffold;
import 'package:flutter/material.dart';
import 'package:global_connect/core/const/responsive_layout.dart';
import '../../Widgets/CustomAppBar.dart';
import '../../core/const/app_color.dart' show AppColors;
import '../../core/theme/app_text_style.dart';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart' show Scaffold;
import 'package:flutter/material.dart';
import 'package:global_connect/core/const/responsive_layout.dart';
import '../../Widgets/CustomAppBar.dart';
import '../../core/const/app_color.dart' show AppColors;
import '../../core/theme/app_text_style.dart';

class TermsOfUseScreen extends StatelessWidget {
  const TermsOfUseScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar2(
        title: Text(
          'Terms of Use',
          style: pjsStyleBlack18600.copyWith(color: AppColors.black),
        ),
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(
          horizontal: context.screenWidth * 0.05,
          vertical: context.screenHeight * 0.02,
        ),
        child: RawScrollbar(
          thumbVisibility: true,
          thickness: 3.0,
          radius: Radius.circular(8.0),
          thumbColor: AppColors.primary,
          trackColor: AppColors.greyScale100,
          trackVisibility: true,
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.only(
                right: 10.0,
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Global Connect Terms of Service Version 1.0, 17/06/2025', style: pjsStyleBlack18600),
                  SizedBox(height: context.screenHeight * 0.02),

                  // Table of Contents
                  _buildTocItem('1. General Terms', '3'),
                  _buildTocSubItem('1.1. Agreement Acceptance', '3'),
                  _buildTocSubItem('1.2. Fees (If Applicable)', '4'),
                  _buildTocSubItem('1.3. Notifications', '5'),
                  _buildTocSubItem('1.4. The Service', '5'),
                  _buildTocItem('2. Right of Use', '6'),
                  _buildTocSubItem('2.1. User Rights and Responsibilities', '6'),
                  _buildTocSubItem('2.2. Third-Party Business Use', '6'),
                  _buildTocSubItem('2.3. API and Developer Access', '7'),
                  _buildTocSubSubItem('General', '7'),
                  _buildTocSubSubItem('Security', '8'),
                  _buildTocSubSubItem('Acceptable Use of Global Connect APIs', '8'),
                  _buildTocSubSubItem('For Developers: Development Accounts and Environments', '9'),
                  _buildTocItem('3. Data Processing', '10'),
                  _buildTocSubItem('3.1. Your Privacy and Transparency', '10'),
                  _buildTocSubItem('3.2. Our Role as Data Controller and Your Data Rights', '10'),
                  _buildTocSubItem('3.3. Usage Data', '11'),
                  _buildTocSubItem('3.4. Subcontractors', '12'),
                  _buildTocSubItem('3.5. Security', '13'),
                  _buildTocItem('4. Supporting terms', '13'),
                  _buildTocSubItem('4.1. Confidentiality', '13'),
                  _buildTocSubItem('4.2. Intellectual Property Rights', '14'),
                  _buildTocSubItem('4.3. Warranty', '15'),
                  _buildTocSubItem('4.4. Liability', '16'),
                  _buildTocSubItem('4.5. Indemnification', '16'),
                  _buildTocSubItem('4.6. Termination', '17'),
                  _buildTocSubItem('4.7. Governing Law and Dispute Resolution', '18'),
                  _buildTocItem('5. Change log', '18'),
                  SizedBox(height: context.screenHeight * 0.03),

                  // Definitions
                  Text('Definitions', style: pjsStyleBlack16400),
                  SizedBox(height: context.screenHeight * 0.02),
                  Text('This document, outlining the rules and conditions for using the Service. Terms may also be used in the plural, e.g., "Parties" or "Users".', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Global Connect | Refers to Global Connect AS, a company registered in Norway with organization number 935687519.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('User | An individual person who accesses or uses the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Service | The Global Connect mobile application and its associated website, including all features, functionalities, content, and related services, as provided by Global Connect. This includes future revisions, modifications, and upgrades.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Service Documentation | Documentation describing Service features, functionality, and configuration, such as help files or in-app guides.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Account | A unique user account created for an individual to access and use the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Fee | Any fees due to Global Connect from the User, where applicable (e.g., for premium features, subscriptions, if introduced).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Subscription Period | The time period for which any applicable fees grant the User a right of use for the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('User Data | All data belonging to the User (or generated by their Use) and processed by the Service. This includes User Content, profile information, usage data, and other forms of data and documents associated with the User\'s interaction with the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Personal Data | Any information relating to an identified or identifiable natural person (Data Subject).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Data Subject | A natural person whose personal data is Processed by a Data Controller or Data Processor.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Special Categories of Personal Data (Sensitive Personal Data) | Any Personal Data related to:\n- Racial or ethnic background\n- Political opinions and affiliations\n- Religious beliefs and other beliefs of a similar nature\n- Trade union membership\n- Mental and physical health, including sex life and sexual orientation\n- Criminal convictions and offenses\n- Genetic and biometric data', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Data Controller | The entity that determines the purposes, conditions and means of the Processing of Personal Data. For the Personal Data of its Users, Global Connect is the Data Controller.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Data Processor | The entity Processing Personal Data on behalf of the Data Controller.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Data Processing or Processing | Any operation or set of operations which is performed on the Data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Breach | A breach of security leading to the accidental or unlawful destruction, loss, alteration, unauthorised disclosure of, or access to, Data transmitted, stored or otherwise Processed.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Data | A collective term for User Data, Personal Data, Sensitive Personal Data, and Usage Data, including data sets, as applicable in context.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Usage Data | Certain data collected from and/or generated from the Service and the use thereof, as specified in Global Connect\'s Privacy Policy.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Use | Any and all actions performed on or with the Service by the User or on their behalf, including the uploading of, entering into or sending or generating of Data.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Partner | A third-party company or entity collaborating with Global Connect to provide or enhance the Service, such as for events, promotions, or data insights.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('User Content | Any data, text, images, photos, videos, audio, location information, tips, chat messages, profiles, and other content or materials that you (the User) submit, post, display, or otherwise make available on or through the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('API | Application Programming Interface.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Third Party Component | Software or intellectual property from a third party that is provided by Global Connect as part of or in connection with the Service', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.03),

                  // 1. General Terms
                  Text('1. General Terms', style: pjsStyleBlack16400),
                  SizedBox(height: context.screenHeight * 0.02),
                  Text('1.1. Agreement Acceptance', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.1.1. You, as a User, access and use the Global Connect Service. You can gain access directly through our website or via mobile application stores (like the Apple App Store or Google Play Store).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.1.2. These Terms of Service ("Terms") are the standard terms that govern your use of the Service. Please read these Terms carefully. By accessing or using the Service, or by clicking "I accept" or similar (e.g., within the app, on our website, or in a confirmation email), you are entering into a legally binding agreement with Global Connect. If you don\'t agree with these Terms, please don\'t use the Service or accept them, as doing so means you\'ve entered into a binding legal agreement with us.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.1.3. These Terms cover the Global Connect Service. Any specific details about fees (if applicable for premium features), how you can manage or end your access, and any other important information will be shown within the Service, on our website, or in direct communications about your account.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.1.4. Unless we specifically agree otherwise in writing, these Terms represent the entire agreement between you and Global Connect regarding the Service. These Terms don\'t cover other services you might purchase from Global Connect or a Partner, such as specific event tickets or promotional offers. Those might have their own specific terms presented at the time of purchase.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.1.5. Global Connect may change these Terms at our discretion, as outlined in Section 1.3.1. The Terms will always show the date of the last update. (You can also check our change log in Section 5). Some changes to these Terms and/or the Service (like those required by new laws) might ask you to re-accept the Terms. We\'ll notify you of such changes at least 30 days in advance, as per Section 1.3.2. If you don\'t accept changes to these Terms, you can stop using the Service according to Section 4.6.1. The latest version of these Terms is always available on our website at www.global-connect.ai', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('1.2. Fees (If Applicable)', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.2.1. Any fees for premium features, subscriptions, or other paid services within Global Connect are based on our current price lists, which we\'ll publish online, within the app, or make available through other means. Keep in mind that some core parts of the Service may be offered free of charge.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.2.2. Unless we explicitly state otherwise or agree to something different in writing, all fees are due in advance and are non-refundable. We typically don\'t offer refunds for unused features, subscription periods, or remaining days, unless a significant part of the Service becomes unavailable or heavily restricted due to reasons solely caused by Global Connect. In such rare cases, we may, at our discretion and as your only remedy, offer a reasonable refund for fees paid during the period of reduced availability.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.2.3. All fees are exclusive of taxes, levies, and duties. Unless we explicitly state otherwise, Global Connect will add any applicable value-added tax (VAT) or other required taxes to your invoice or charge.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.2.4. Global Connect reserves the right to change our fees, including how we charge for features, by giving you 3 months\' notice as described in Section 1.3.1. We won\'t do this more than twice a year for any single paid feature. We may also increase prices with 1 month\'s notice if a subcontractor raises their prices towards us. Additionally, we may increase prices annually to account for general price and cost increases without individual notification; these annual price changes usually take effect from January 1st each year, unless stated otherwise.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.2.5. If you don\'t pay your fees on time, Global Connect reserves the right to suspend or limit your access to paid features or even the entire Service (e.g., restricting access to read-only mode), as mentioned in Section 4.6.2. We may also charge penalty interest up to the maximum rate allowed by law. Unpaid invoices may be sent to collections. If a payment issue isn\'t resolved within a reasonable time, Global Connect reserves the right to terminate your right to use the affected Service, as per Section 4.6.2.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('1.3. Notifications', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.3.1. We\'ll send general notifications and information about the Service – like new features, price changes, or planned maintenance – directly inside the app, on our website, through our online community, or by email.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.3.2. For important information specific to your account, such as confirmations or critical updates related to security or privacy, we\'ll send a notification to your primary contact email on file.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.3.3. You\'re responsible for making sure Global Connect always has your current contact information, including your primary email address.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.3.4. All notices are considered received as soon as we send or post them. Unless we state otherwise in the notice, all notices are effective immediately.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('1.4. The Service', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.4.1. When you get access to Global Connect, you\'re buying a right to use the Service as we make it available online. This means you can use the app and website as described in these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.4.2. Global Connect will provide free operational support for basic issues like login problems or errors in the app. If you need more support, like user training, that might be something you can buy separately from us or a Partner (if we offer it).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.4.3. The Service is provided "as is" as a standard mobile app and online platform. We don\'t promise any specific future versions or features at any particular time, nor are we bound by any previous comments or publications. You can use the online Service as it\'s provided at any given moment.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.4.4. Global Connect can improve, add, change, or remove features, or fix any errors in the Service at our sole discretion, without any obligation or liability. In the unlikely event that a change permanently disables or removes a core part of the Service for more than 2 months, you might be able to end your subscription for any affected paid features. In that case, you\'d receive a pro-rated refund for fees paid in advance for that period.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.4.5. Global Connect reserves the right to stop offering the Service, or stop making it available in a certain market, with 12 months\' prior notice. If this happens, you\'ll get a pro-rated refund for any fees paid in advance for the period after the Service stops. You must also stop using the Service after that date and won\'t have any further claims against Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('1.4.6. Some features in the Service might have additional terms or limits (like on chat history or number of friends) or might require you to register on other websites (like for a payment or event ticketing service). We\'ll tell you about these additional terms either within the Service or in specific communications.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.03),

                  // 2. Right of Use
                  Text('2. Right of Use', style: pjsStyleBlack16400),
                  SizedBox(height: context.screenHeight * 0.02),
                  Text('2.1. User Rights and Responsibilities', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.1.1. As a user of Global Connect, you get a limited, non-exclusive, revocable, and terminable right to access and use our Service. This right is for your personal, non-commercial use only and must always be in line with these Terms of Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.1.2. To be clear, "personal, non-commercial use" means using the Service for your own enjoyment, travel, and social interactions. It does not mean you can use the Service to run a business, offer services to others, or for any commercial activities that are not expressly approved by Global Connect. You cannot use the Service for any entity you own or control, unless otherwise agreed in writing.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.1.3. Your right to use the Service cannot be transferred or given to anyone else under any circumstances (including mergers, bankruptcy, or changes of ownership) without Global Connect\'s prior written permission, which we won\'t unreasonably withhold.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.1.4. You are solely responsible for all your actions when using the Service. This includes what you do, how you manage your account, and any access or integrations made by others or third-party applications on your behalf. You are also solely responsible for the content you post and its legality. You agree not to upload or process any harmful code or data (like viruses) or use the Service for any unlawful or malicious purposes.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.1.5. You are responsible for your own user account and how it\'s used. Each account is meant for a single named individual only and cannot be shared.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('2.2. Third-Party Business Use', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.2.1. The Global Connect Service is primarily intended for personal, non-commercial use by individual users. If you wish to use the Service, or any part of it, for business operations, commercial promotion, or on behalf of any other entity (such as a restaurant, event organizer, or service provider), you must obtain prior written approval from Global Connect. Specific terms and agreements will apply to such commercial uses.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.2.2. If you are authorized by Global Connect to use the Service for commercial purposes (e.g., as a registered Partner for promotions), your right to access and use the Service for such purposes is limited, non-exclusive, revocable, and terminable. This right is solely and exclusively for providing your authorized commercial services or promotions in accordance with a separate agreement with Global Connect and these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.2.3. You are solely responsible for all your commercial Use of the Service, including any content you upload, promote, or links you share related to your business. You must ensure that all such content and activities comply with these Terms, all applicable laws and regulations, and any specific partner agreements with Global Connect. You shall not transfer or process harmful code, data, or similar (such as viruses) to or with the Service, nor use the Service for unlawful or malicious purposes.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.2.4. You may not act or give the impression that you are a producer, owner, reseller, or distributor of Global Connect, nor enter into any warranty or representation on behalf of Global Connect or concerning the Service, except as expressly set forth herein or in a separate partner agreement.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.2.5. You shall indemnify Global Connect from all claims, costs, and expenses resulting from claims or requests made by any third party directly towards Global Connect, arising from your commercial use of the Service or any breach of these Terms by you.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('2.3. API and Developer Access', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('General', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.1. Global Connect may, at its discretion, grant you a limited, non-exclusive, revocable, and non-transferable right to use Global Connect\'s Application Programming Interfaces (APIs). This is typically for the purpose of integrating other software applications or services with our Service ("Integrated Applications").', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.2. Global Connect APIs are provided "as is". While we will strive to inform you about significant changes to our APIs in advance, Global Connect reserves the right to modify or discontinue its APIs and/or their support at its sole discretion at any time, without any obligation or liability. Modifications might require your Integrated Application to use a supported version of the API.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.3. Global Connect reserves the right to charge fees for any API usage or access to development environments in the future, including making the right of use dependent upon such payments.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.4. Global Connect claims no ownership or control over your applications or systems, except to the extent such applications or systems contain intellectual property owned by Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.5. Any unauthorized use of an API or development account/environment may lead to immediate deactivation of the account, revocation of your right to use the API, and may also result in termination of your access to the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.6. You may terminate your right to use Global Connect\'s API at any time by simply stopping your use of the API.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Security', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.7. If you integrate with Global Connect\'s APIs, you must ensure that your Integrated Application and related systems (like web servers and databases) are configured to provide appropriate security. This includes organizational, technical, and physical security measures designed to protect the confidentiality, integrity, availability, and resilience of the application, the Service, and any data involved.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.8. You must report any security or data breaches (like intrusions, unauthorized access, or discovery of a vulnerability) without undue delay to Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Acceptable Use of Global Connect APIs', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.9. Your use of Global Connect APIs must not violate any law or regulation or infringe upon the individual rights of any person, including privacy rights and intellectual property rights.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.10. Any Integrated Application using our APIs should ideally be of a complimentary or value-added nature to Global Connect\'s services and users.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.11. Global Connect APIs may be used for commercial purposes, however: a) Direct access to or use of the Global Connect API may not be provided, sublicensed, sold, transferred, or otherwise made available to third parties (except direct users of your Integrated Application) or circumvented. b) Data obtained from Global Connect APIs may not be aggregated or syndicated for the purpose of selling, transferring, or making such data available in any form to parties other than your Integrated Application\'s end users for their internal business purposes.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.12. You must not place advertising or other third-party content within Global Connect\'s Service via an API. Data or other content from Global Connect\'s Service may not be used for advertising, including in particular user profiling, in your Integrated Application or elsewhere, unless explicitly authorized by Global Connect and based on an appropriate legitimate basis.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.13. You shall not transfer or process harmful code, data, or similar (such as viruses) to or with the Global Connect API, nor use the API for unlawful or malicious purposes.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.14. You must not give the impression that your Integrated Application or its use of the Global Connect API is associated with, sponsored by, or endorsed by Global Connect, except after express prior approval from Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('For Developers: Development Accounts and Environments', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.15. Access to and use of Global Connect\'s development environments (if available) by developers typically requires you to enter into a specific developer or partner agreement with Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.16. Upon such agreement, you are granted a limited, non-exclusive, revocable, non-transferable, and terminable right to use Global Connect\'s development environments and APIs to integrate, develop, test, and support your (or your customers\') Integrated Applications with the Global Connect Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.17. Documentation, data, and information regarding the use of Global Connect\'s APIs and development environments will be made available. It\'s your responsibility to stay updated with and abide by such documentation, which may vary.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.18. If there\'s a conflict between any additional terms for a particular development environment/API documentation and these general Terms, the additional terms will take precedence.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.19. Development account access is for named individual users only and may not be shared. Registration for a developer account must be performed manually, not by scripts.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.20. After registering for a development account, you will be given necessary security keys, tokens, or other credentials to access and use Global Connect\'s development environments and APIs. These are used to authenticate your API activity with your Integrated Applications.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.21. You are responsible for the confidentiality and all use of your API Credentials and all use of Global Connect\'s development environments. API Credentials must be kept confidential and may not be sublicensed, sold, transferred, or otherwise made available to third parties, nor circumvented.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.22. Development environments must not be used as production environments; they are solely for testing, development, and support of Integrated Applications. If the development environment supports test accounts, these must not interact with any non-test accounts.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.23. You shall not transfer or process harmful code, data, or similar (such as viruses) to or with the development environments, nor use them for unlawful or malicious purposes.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.24. Development environments are provided "as is." While Global Connect will strive to inform about changes in advance, we reserve the right to modify, delete, restore, or discontinue any development environment or part thereof (including data), and/or their support, as well as placing limits and restrictions, at our sole discretion at any time, without any obligation or liability.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.25. You shall not obscure or hide any Global Connect communications, sign-in functionality, or authorization flows from users, nor communicate with users in a manner that might reasonably confuse them into thinking it\'s a message from Global Connect or its personnel.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.26. If your Integrated Application is used by others outside your organization, you must maintain an appropriate user agreement and privacy policy for your application, considering your obligations under these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('2.3.27. Global Connect\'s APIs and API Credentials may not be used to help or enable governmental authorities to get access to data in a way that would break Global Connect\'s general confidentiality obligations for its users\' data or obligations as a Data Processor, such as by avoiding serving legal process directly to Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.03),

                  // 3. Data Processing
                  Text('3. Data Processing', style: pjsStyleBlack16400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Global Connect is committed to ensuring that our Service is compliant with all applicable data protection laws and regulations, including the General Data Protection Regulation (GDPR).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),
                  Text('3.1. Your Privacy and Transparency', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.1.1. Transparency and accountability are very important to us at Global Connect. We provide detailed information about how we process your personal data in our Privacy Policy (or Privacy Statement). This policy outlines exactly what personal data we collect, why we collect it, how we use it, who we share it with, and your rights regarding your data. It also includes information about the service providers and subcontractors we use to process your data, and where our data centers are located.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Our full Privacy Policy is always available on our website at www.global-connect.ai', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('You can also contact our Data Protection Officer (if applicable) or our privacy team directly with any questions regarding data processing at: hello@global-connect.ai', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('3.2. Our Role as Data Controller and Your Data Rights', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.2.1. For the personal data we collect from you through the Global Connect Service, Global Connect acts as the Data Controller. This means we determine the purposes and means of processing your personal data, as further detailed in our Privacy Policy. As the Data Controller, we are responsible for ensuring that your data is processed in accordance with applicable data protection laws, including the General Data Protection Regulation (GDPR).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.2.2. As the Data Controller, we commit to: a) Processing your personal data fairly, lawfully, and transparently. b) Collecting personal data for specified, explicit, and legitimate purposes, and not processing it further in a manner that is incompatible with those purposes. c) Ensuring that the personal data we collect is adequate, relevant, and limited to what is necessary in relation to the purposes for which it is processed. d) Maintaining appropriate technical and organizational measures to protect your personal data from unauthorized or unlawful processing and against accidental loss, destruction, or damage. e) Notifying the relevant supervisory authorities and, if required by law, you, in the event of any personal data breach, without undue delay after becoming aware of it. f) Responding to your requests regarding your data rights (as outlined in our Privacy Policy) in a timely manner. g) Deleting or returning your personal data when our legal basis for processing it expires, or upon your valid request, unless mandatory provisions of law require continued storage.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.2.3. You, as the User (Data Subject), have certain rights regarding your personal data under GDPR. These rights are fully explained in our Privacy Policy, including your right to access, rectify, erase, restrict processing of, and object to the processing of your personal data, as well as the right to data portability. You also have the right to lodge a complaint with a supervisory authority.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.2.4. For full details on how Global Connect processes your personal data, including the types of data collected, the purposes of processing, the legal basis for processing, how data is shared, and your rights, please refer to our dedicated Privacy Policy.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('3.3. Usage Data', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.3.1. Usage Data refers to certain data generated by your use of the Global Connect Service. We collect and use this data to protect the Service and your data, to provide, market, develop, and maintain the Service and related products. By using the Service, you grant Global Connect the right to use any Usage Data you may own, as specified in this section 3.3.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Usage Data includes:', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.005),
                  Text('● Technical information: Such as your operating system type, browser type, device details, and IP address.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.005),
                  Text('● Aggregated usage metrics: Such as session durations, number of interactions with features (e.g., clicks on tips or events), and overall activity patterns within the app.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.005),
                  Text('● Non-aggregated user-generated data: This might include the context of support tickets, crash logs, and security-related logs.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('We may also combine Usage Data with relevant information from publicly available or commercially sourced data to improve functionality, such as providing lookup features for businesses or locations.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.3.2. Personal Data within Usage Data: Where Usage Data contains Personal Data (such as an IP address, or details about you as a user), Global Connect is the Data Controller for such Personal Data. We process this based on our legitimate interests in providing and improving the Service. We implement technical and organizational security measures to achieve a level of security appropriate to the risks involved in this processing.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('We aim to anonymize such data through technical processes before using it for the purposes below, so that the data is no longer Personal Data and you, the User, can no longer be identified. If anonymization is not technically possible or feasible for specific processing purposes, we implement additional appropriate security measures. Usage Data is not used for any purpose that would legally require explicit consent from you as an individual Data Subject.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('You have the right to extensive information about how Global Connect processes Usage Data, including your right to object to such processing, as detailed in our Privacy Policy.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.3.3. Usage Data, including any limited production data (if applicable), is processed solely for the following purposes: a) Service and User Experience Improvement: For example, by analyzing aggregate usage patterns to enhance features, enable individual user preferences, or develop predictive functionalities. b) Marketing and Relevant Information: To market and display information about complimentary or value-adding features within the Service, or to provide relevant updates and offers. c) Security and Related Purposes: By analyzing session and login data (including in real-time) and incident records to prevent, investigate, and document security issues (such as breaches, fraud, and various forms of hacking), and to improve the security of the Service. d) Statistics and Research: For example, creating aggregated and anonymized statistics for general marketing or for offering value-adding insights within the app. e) Compliance: To analyze Usage Data for compliance with these Terms, for example, logging when you accept these Terms. f) Development and Testing: By analyzing aggregate usage patterns to provide data for developing new technologies, improving user experience, or for testing new or updated Service functionalities.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Global Connect may share Usage Data with other companies within the Global Connect group (if applicable) and with trusted Partners, subject to the same terms and limitations set forth herein and in our Privacy Policy.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('3.4. Subcontractors', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.4.1. Global Connect may use other Global Connect companies (if applicable) and third-party subcontractors to provide and develop the Service. This includes their processing of Personal Data and/or Usage Data on our behalf. Global Connect will always enter into a data processing agreement with these subcontractors to ensure they meet the obligations set out in our Privacy Policy and these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.4.2. If our subcontractors are located outside the EU/EEA, we ensure there are legal grounds for the transfer of Personal Data out of the EU/EEA. This is done using appropriate legal mechanisms, such as Standard Contractual Clauses (SCCs) or other approved frameworks, to ensure your data receives adequate protection.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.4.3. We will strive to notify you of any planned changes to our subcontractors in advance. While you may object to the use of a subcontractor on reasonable grounds, due to the nature of an online service, you may not be able to opt out of the use of certain subcontractors. In such an event, you may choose to terminate your use of the Service according to Section 4.6.1.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('3.5. Security', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('3.5.1. Global Connect is fully committed to providing a high level of security for our Service, including robust protections for your personal data and privacy. We implement appropriate organizational, technical, and physical security measures. These are designed to ensure the confidentiality, integrity, availability, and resilience of the Service and all data processed through it.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('Because IT security, especially online, is constantly evolving, we provide a more detailed description of our security measures in our Privacy Policy. You can also reach out to us directly at hello@global-connect.ai for more information about security within our Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.03),

                  // 4. Supporting terms
                  Text('4. Supporting terms', style: pjsStyleBlack16400),
                  SizedBox(height: context.screenHeight * 0.02),
                  Text('4.1. Confidentiality', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.1.1. In connection with this agreement, either you or Global Connect might share or get Confidential Information from the other party. This includes, but isn\'t limited to, trade secrets, technology, data, business plans, and any other information that should reasonably be considered private or competitively sensitive ("Confidential Information"). Both parties agree to keep all Confidential Information private and to protect it with reasonable care. We won\'t share it with anyone else unless the other party specifically says so in writing, or if required by law. All rights and ownership of Confidential Information belong exclusively to the party that shared it.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.1.2. Confidential Information does not include information that: a) The receiving party already knew or had before accepting these Terms and lawfully acquired; b) Becomes publicly available without any fault, action, or omission from the receiving party; c) The receiving party gets from a third party without any confidentiality obligation; or d) Is developed independently by the receiving party without breaking these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.1.3. Unless stated otherwise in these Terms, Global Connect will not sell, rent, lease, or otherwise make your User Data or Usage Data available to third parties except in situations like: * To follow any law, regulation, or directive, or to respond to a legally binding request from government authorities or the police (like a court order or warrant); * To investigate or prevent serious security threats or fraud; * If Global Connect (or parts of it) undergoes a reorganization, merger, sale, or purchase, Confidential Information may be shared with other companies within the Global Connect group or with actual or potential buyers. In all such cases, Global Connect will make sure these parties follow confidentiality obligations through a confidentiality agreement.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.1.4. Global Connect may share Confidential Information with other companies within the Global Connect group (if applicable), Partners, or subcontractors, but only as much as is needed to provide the Service and fulfill our obligations under these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('4.2. Intellectual Property Rights', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.2.1. Global Connect (or its licensors, where applicable) is the sole owner of the Service and all related intellectual property rights (IPR). This includes, but isn\'t limited to, the source code, object code, databases, designs, documentation, and any IPR that comes from our processing of Usage Data. The Service and its IPR are protected by copyright and other applicable laws and treaties. Trademarks, product names, company names, or logos mentioned in connection with the Service that are not ours are the property of their respective owners.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.2.2. If any software or other IPR from a third party is included as part of or with the Service ("Third-Party Components"), those components are covered by these Terms unless separate terms are provided by Global Connect. If there\'s a conflict between the licensing terms of a Third-Party Component and these Terms, the Third-Party Component\'s terms will apply to that specific component. If a Third-Party Component is open source, that doesn\'t mean the rest of our Service is open source or publicly available. If a Third-Party Component requires us to provide its license terms or source code, you\'ll find this information in the Service\'s "About" section or in our Service documentation.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.2.3. If anyone infringes on our intellectual property rights, Global Connect (or its licensors) may take all reasonable steps to protect its legal and business interests, including any remedies allowed by law.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.2.4. You, the User, are the sole owner of your User Data, including any intellectual property rights in that data. This also applies to any content you create or upload through the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('4.3. Warranty', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.1. Global Connect will use commercially reasonable efforts to ensure that the Service performs largely as described in our Service Documentation during your subscription period (if applicable). This assumes you\'ve properly configured your device and are using a supported version of the app. We and you agree that the Service won\'t be entirely free of errors, and improving the Service is an ongoing process.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.2. Global Connect doesn\'t guarantee that the Service will meet all your specific requirements, work perfectly with your chosen equipment or settings, or always be uninterrupted if delivered over the internet. Global Connect isn\'t responsible for the internet itself, your internet service provider, or your internet connection.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.3. If the Service doesn\'t work as described in this limited warranty, Global Connect will fix confirmed errors or defects at our own expense. A "confirmed error or defect" means one that we can reproduce and/or confirm through our support channels, and which happens during your active use or subscription period. We might choose to replace the faulty feature or part of the Service instead of fixing it directly.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.4. If a confirmed error or defect is serious enough to significantly reduce your ability to use a material part of the Service, and Global Connect doesn\'t fix it or provide a replacement within a reasonable time, you may be able to end your right to use the affected part of the Service. In such a case, you\'d be entitled to a pro-rated refund for any fees paid in advance for the remaining subscription period for that affected Service, starting from the month after we verify the error.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.5. Except as explicitly stated in these Terms, you won\'t be able to make any other claims against Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.6. Aside from what\'s expressly laid out in these Terms, neither Global Connect nor its licensors offer any other warranties, whether express or implied. This includes, without limitation, warranties of title, non-infringement, merchantability (fitness for sale), fitness for a particular purpose, or system integration capability. You can\'t make claims based on anything not expressly written in these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.3.7. Links to websites that aren\'t owned or controlled by Global Connect, which appear in the Service or related webpages/documentation, are provided only for your convenience. Global Connect isn\'t responsible for such external websites.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('4.4. Liability', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.4.1. Global Connect isn\'t responsible or liable for your User Data, including its content, ownership, or legality. We\'re also not responsible for any use or actions you perform with your User Data or through the Service that are outside of our control.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.4.2. If Global Connect is found responsible for compensation due to breaking any of our obligations in these Terms, that compensation won\'t include indirect or consequential losses or damages. This means we\'re not liable for things like lost data, lost income or profits, or claims from third parties or government sanctions, even if we\'ve been told such damages might happen. Our liability under these Terms is limited to direct damages only, unless otherwise required by law (like damages caused by gross negligence or willful misconduct).', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.4.3. Our total, accumulated liability (including any refunds and compensation for direct losses and costs) during your Subscription Period for any affected paid features of the Service won\'t be more than 12 months\' worth of fees for that specific feature.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.4.4. Neither Global Connect nor you will be liable for any delays or failures that happen because of force majeure events. This includes things like earthquakes, riots, labor disputes, internet issues, changes in internet laws or operations, and other similar events outside our control. If new laws or regulations come out after the Service is available that prevent us from fulfilling our obligations or require us to suspend the Service, completely or partly, that will also count as a force majeure event.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.4.5. While Global Connect will take reasonable care to keep information secure when transmitted between you and the Service, you understand that the internet is an open system. This means Global Connect can\'t and doesn\'t guarantee that third parties won\'t intercept or change your data. Global Connect accepts no liability for such misuse, disclosure, or data loss.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('4.5. Indemnification', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.5.1. Global Connect will defend you against any claim or lawsuit from a third party that says your use of the Service, under these Terms, infringes on their patent, copyright, or other intellectual property right. You must tell Global Connect about any such claim right away. Global Connect will cover any damages awarded to the third party through a court-approved settlement or ruling, including lawyer fees. This is provided that you cooperate with Global Connect at our expense and give us full control of the legal process and settlement. Global Connect may, at our discretion, (i) change the Service so it no longer infringes, (ii) replace the Service with something functionally similar, (iii) get a license for your continued use of the Service, or (iv) end your right to use the Service with a refund for any fees paid in advance for periods after termination. You can\'t make any other claims because of such infringement.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.5.2. The above promise to defend won\'t apply if the Service was used in violation of these Terms, including if the claim comes from any use, change, integration, or customization of the Service that wasn\'t done by Global Connect.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.5.3. You will defend Global Connect against any claim or lawsuit where a third party claims that your User Data, or your use of the Service in violation of these Terms, conflicts with or infringes on their patent, copyright, or other intellectual property rights, or violates applicable law. Global Connect will tell you about any such claim right away. You will cover any damages awarded through a court-approved settlement or ruling, including lawyer fees. This is provided that Global Connect cooperates with you at your expense and gives you full control of the legal process and settlement.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('You will also indemnify Global Connect from all claims, fines, and sanctions that result from your breach of your obligations regarding the processing of Personal Data.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('4.6. Termination', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.6.1. Termination by You (the User): You can end your use of the Global Connect Service, or any individual paid features, at any time. The specific terms for doing so will be available within the app or on our website.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.6.2. Termination by Global Connect: If we confirm or reasonably suspect that you\'ve violated any of your obligations under these Terms, or if you become bankrupt or insolvent, Global Connect may suspend or limit your access to the Service (e.g., to read-only mode) until the issue is resolved. We\'ll give you 30 days\' notice before any suspension or restriction and give you reasonable time to respond. If the issue isn\'t resolved within a reasonable time, Global Connect reserves the right to end your right to use the Service, thereby terminating your account. Global Connect may, at its sole discretion, choose to terminate your right to use the Service immediately if you are in material (serious) breach of these Terms.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.6.3. Data Deletion Upon Termination: When your account is terminated, or if our legal basis for processing your data expires for any reason, Global Connect will delete your User Data from our systems, unless we\'re legally required to keep it for a longer period. If data must be stored longer by law, we\'ll continue to maintain its security as outlined in these Terms. The exact time it takes to delete data may vary. After deleting your User Data, Global Connect will have no further obligations to you regarding that data.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.6.4. Data Return: You may request the return of your User Data no later than 30 days after termination. If more than 30 days have passed, your data may have been permanently deleted. Global Connect will return your User Data in a format and by a method determined by us. The specific format and method may vary, so please contact Global Connect\'s privacy team at hello@global-connect.ai well before terminating your account to plan for data return. Some features within the Service may also offer functionality for you to export your data directly.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.02),

                  Text('4.7. Governing Law and Dispute Resolution', style: pjsStyleBlack14600),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.7.1. Your agreement to these Terms is made with Global Connect, Global Connect AS, registered in Norway, Org. No. 935687519.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.7.2. These Terms and your use of the Service are fully governed by the laws of Norway, without regard to its conflict of law principles. If any dispute comes up related to these Terms or your use of the Service, we\'ll both try to resolve it through friendly negotiations first. If we can\'t settle the dispute this way, it will be brought before the ordinary courts of law in Norway, with Kristiansand District Court as the exclusive legal venue.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.7.3. Neither you nor Global Connect can bring any claims related to these Terms if more than one year has passed after the termination of your use of the Service.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('4.7.4. If there\'s any doubt about the interpretation between these Terms in English and any version translated into another language, the English version will take precedence.', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.03),

                  // 5. Change log
                  Text('5. Change log', style: pjsStyleBlack16400),
                  SizedBox(height: context.screenHeight * 0.01),
                  Text('- No changes. This is the first version, published 17.06.2025', style: pjsStyleBlack14400),
                  SizedBox(height: context.screenHeight * 0.03),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
  Widget _buildTocSubItem(String title, String page) {
    return Padding(
      padding: EdgeInsets.only(left: 16, top: 2, bottom: 2),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Text(title, style: pjsStyleBlack12400),
          ),
          Text(page, style: pjsStyleBlack12400),
        ],
      ),
    );
  }
  Widget _buildTocItem(String title, String page) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 2),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Text(title, style: pjsStyleBlack14600),
          ),
          Text(page, style: pjsStyleBlack14400),
        ],
      ),
    );
  }
  Widget _buildTocSubSubItem(String title, String page) {
    return Padding(
      padding: EdgeInsets.only(left: 32, top: 2, bottom: 2),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Text(title, style: pjsStyleBlack12400),
          ),
          Text(page, style: pjsStyleBlack12400),
        ],
      ),
    );
  }
}
