// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl4BexppTULCNdwQ_r6Dt6nbvisuVWmLY',
    appId: '1:148336024959:web:3a5c6939c39dbab2f44e4a',
    messagingSenderId: '148336024959',
    projectId: 'global-connect-7c86b',
    authDomain: 'global-connect-7c86b.firebaseapp.com',
    storageBucket: 'global-connect-7c86b.firebasestorage.app',
    measurementId: 'G-2PHPZ8ZPVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJRnFCdUr8DTmHRCgs4dwWgqZ75CvWRFs',
    appId: '1:148336024959:android:ff14597576a7b385f44e4a',
    messagingSenderId: '148336024959',
    projectId: 'global-connect-7c86b',
    storageBucket: 'global-connect-7c86b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK-CF7LtLnxs1Dh1Fv0dgtK_egHhFonuU',
    appId: '1:148336024959:ios:817f376ce7b4cc43f44e4a',
    messagingSenderId: '148336024959',
    projectId: 'global-connect-7c86b',
    storageBucket: 'global-connect-7c86b.firebasestorage.app',
    androidClientId: '148336024959-f83ca4nnua2m70dth269glft11u21njc.apps.googleusercontent.com',
    iosClientId: '148336024959-c25u1t62bplbs499mn0qjr0cv2d6h34c.apps.googleusercontent.com',
    iosBundleId: 'com.example.globalConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl4BexppTULCNdwQ_r6Dt6nbvisuVWmLY',
    appId: '1:148336024959:web:3a5c6939c39dbab2f44e4a',
    messagingSenderId: '148336024959',
    projectId: 'global-connect-7c86b',
    authDomain: 'global-connect-7c86b.firebaseapp.com',
    storageBucket: 'global-connect-7c86b.firebasestorage.app',
    measurementId: 'G-2PHPZ8ZPVP',
  );

}